<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>GraviSharp.UI</RootNamespace>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="8.0.0" />
    <TrimmerRootDescriptor Include="TrimmerRoots.xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GraviSharp.Core\GraviSharp.Core.csproj" />
  </ItemGroup>
</Project>
